_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.5
            "5": 0.19.0
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
C:
    value: 500
batch:
    value: 64
epochs:
    value: 100000
learning_rate:
    value: 0.1
